# Generated by Django 4.0.4 on 2022-07-06 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='productos/media', verbose_name='Imagen')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT')),
                ('dv', models.IntegerField(verbose_name='DV')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('contacto', models.IntegerField(verbose_name='Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='productos/media', verbose_name='Imagen')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('total', models.IntegerField(verbose_name='Precio')),
                ('cocinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.cocinero')),
                ('comidas', models.ManyToManyField(to='productos.comida')),
            ],
        ),
    ]
