# Generated by Django 4.0.1 on 2022-05-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('idCocinero', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('orders', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idComida', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('pasta', 'pasta'), ('sopa', 'sopa'), ('ensalada', 'ensalada')], max_length=50)),
                ('estado', models.CharField(choices=[('Disabled', 'Disabled'), ('Enabled', 'Enabled')], max_length=50)),
                ('descripcionCont', models.TextField()),
                ('precioBase', models.FloatField()),
                ('precioOferta', models.FloatField(default=models.FloatField())),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('imagen', models.ImageField(upload_to='')),
                ('num_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idOrden', models.IntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('cocinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.cocinero')),
            ],
        ),
    ]
