# Generated by Django 4.0.1 on 2022-05-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comida',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cocinero',
        ),
        migrations.DeleteModel(
            name='Cocinero',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
