# Generated by Django 4.0.4 on 2022-07-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='bebidas',
            field=models.ManyToManyField(to='productos.bebida'),
        ),
    ]
