# Generated by Django 4.0.1 on 2022-05-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_delete_comida_remove_orden_cocinero_delete_cocinero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('rut_cocinero', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_cocinero', models.IntegerField()),
                ('correo_cocinero', models.CharField(max_length=100, verbose_name='correo')),
                ('contacto_cocinero', models.IntegerField(verbose_name='contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idComida', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion_comida', models.CharField(max_length=500)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('cocinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.cocinero')),
                ('idComida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.comida')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_orden', models.CharField(max_length=500)),
                ('monto_total', models.IntegerField()),
                ('num_order', models.IntegerField(default=0)),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.orden')),
            ],
        ),
    ]
