# Generated by Django 4.0.4 on 2022-07-07 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0002_orden_bebidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Precio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.bebida')),
                ('cocinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.cocinero')),
                ('comidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.comida')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.pedido')),
            ],
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
