# Generated by Django 4.0.1 on 2022-05-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='imagen',
        ),
    ]
