# Generated by Django 4.0.4 on 2022-05-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0006_remove_detalleorden_idorden_remove_orden_cocinero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('rut_cocinero', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUN')),
                ('dv_cocinero', models.IntegerField(verbose_name='Dígito verificador')),
                ('correo_cocinero', models.CharField(max_length=100, verbose_name='Correo')),
                ('contacto_cocinero', models.IntegerField(verbose_name='Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idComida', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='products/media', verbose_name='Imagen')),
                ('descripcionComida', models.CharField(max_length=500, verbose_name='Descripción')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100, verbose_name='Nombre')),
                ('contrasena', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idOrden', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('cocinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.cocinero')),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.comida')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalleOrden', models.CharField(max_length=500)),
                ('montoTotal', models.IntegerField()),
                ('numOrden', models.IntegerField(default=0)),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.orden')),
            ],
        ),
    ]
